//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Diagnostics;
using System.Reflection;
using System.Text;
using System.Media;

namespace Plugin.HCR {
	public class Display {
 
		public Display() {
			
		}

		public static void printDebug(int debugLevel,string str) {
			if ((Configuration.getInstance().isEnabledDebugLevel.get() == 0) || (debugLevel < Configuration.getInstance().isEnabledDebugLevel.get()))
				return;
			
			GUIManager gm = AManager<GUIManager>.getInstance();
			gm.AddTextLine(Configuration.getInstance().confName+":DBG: "+str);
		}
		
		public static void printTrace(int traceLevel, int position) {
			if ((Configuration.getInstance().isEnabledTraceLevel.get() == 0) || (traceLevel < Configuration.getInstance().isEnabledTraceLevel.get()))
				return;
			
			GUIManager gm = AManager<GUIManager>.getInstance();
			StackTrace st = new StackTrace();
			StackFrame[] frames = st.GetFrames();
			gm.AddTextLine(Configuration.getInstance().confName+":TRC: " + frames[1].GetMethod().Name+": "+position.ToString());
			
		}
		
		public static void printTrace(int traceLevel, string str = "") {
			if ((Configuration.getInstance().isEnabledTraceLevel.get() == 0) || (traceLevel < Configuration.getInstance().isEnabledTraceLevel.get()))
				return;
			
			GUIManager gm = AManager<GUIManager>.getInstance();
			StackTrace st = new StackTrace();
			StackFrame[] frames = st.GetFrames();
			gm.AddTextLine(Configuration.getInstance().confName+":TRC: " + frames[1].GetMethod().Name+": "+str);
		}
		
		public static void printException(Exception e) {
			GUIManager gm = AManager<GUIManager>.getInstance();
			gm.AddTextLine(Configuration.getInstance().confName+":EXC: " + e.ToString());
			StackTrace st = new StackTrace(e);
			StackFrame[] frames = st.GetFrames();
			foreach(StackFrame frame in frames) {
				//gm.AddTextLine(" in: " + frame.GetMethod().Name + " at line "+frame.GetFileLineNumber().ToString());
				gm.AddTextLine(" in: " + frame.GetMethod().Name);
			}
		}
		
		public static void printErr(string str) {
			GUIManager gm = AManager<GUIManager>.getInstance();
			gm.AddTextLine(Configuration.getInstance().confName+":ERROR: " + str);
		}

		public static void printMsg(string str) {
			GUIManager gm = AManager<GUIManager>.getInstance();
			gm.AddTextLine(Configuration.getInstance().confName+" "+str);
		}

		public static void beep() {
			SystemSounds.Beep.Play();
		}
		
	}
}

